// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.example.com/support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/brands": {
            "get": {
                "description": "Retrieve a list of all available product brands",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metadata"
                ],
                "summary": "Get all available brands",
                "responses": {
                    "200": {
                        "description": "Brands retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "description": "Retrieve a list of all available product categories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metadata"
                ],
                "summary": "Get all available categories",
                "responses": {
                    "200": {
                        "description": "Categories retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the API is running and healthy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "API is healthy",
                        "schema": {
                            "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "description": "Retrieve all products with optional filtering by category and price range",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get all products",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"Smartphones\"",
                        "description": "Filter by category",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "example": 100,
                        "description": "Minimum price filter",
                        "name": "min_price",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "example": 2000,
                        "description": "Maximum price filter",
                        "name": "max_price",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Products retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/domain.Product"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/products/compare": {
            "get": {
                "description": "Retrieve and compare multiple products by their IDs for feature comparison",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Compare multiple products",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"PHONE001,PHONE002,PHONE003\"",
                        "description": "Comma-separated product IDs",
                        "name": "ids",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Products comparison retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid product IDs or insufficient products for comparison",
                        "schema": {
                            "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                        }
                    },
                    "404": {
                        "description": "One or more products not found",
                        "schema": {
                            "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/products/search": {
            "get": {
                "description": "Search for products by name, description, brand, or category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Search products",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"Samsung Galaxy\"",
                        "description": "Search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Products search completed successfully",
                        "schema": {
                            "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid or missing search query",
                        "schema": {
                            "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "get": {
                "description": "Retrieve detailed information about a specific product by its unique identifier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get a product by ID",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"PHONE001\"",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Product retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/domain.Product"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid product ID",
                        "schema": {
                            "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Product not found",
                        "schema": {
                            "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/meli-products-api_pkg_response.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Product": {
            "description": "Product model for comparison",
            "type": "object",
            "required": [
                "description",
                "image_url",
                "name",
                "price",
                "rating"
            ],
            "properties": {
                "available": {
                    "description": "Availability status",
                    "type": "boolean",
                    "example": true
                },
                "brand": {
                    "description": "Brand of the product",
                    "type": "string",
                    "example": "Samsung"
                },
                "category": {
                    "description": "Category of the product",
                    "type": "string",
                    "example": "Smartphones"
                },
                "description": {
                    "description": "Detailed description of the product",
                    "type": "string",
                    "example": "Latest Samsung flagship smartphone with advanced camera technology"
                },
                "id": {
                    "description": "Unique identifier for the product",
                    "type": "string",
                    "example": "PHONE001"
                },
                "image_url": {
                    "description": "URL of the product image",
                    "type": "string",
                    "example": "https://images.example.com/samsung-s24.jpg"
                },
                "name": {
                    "description": "Name of the product",
                    "type": "string",
                    "example": "Samsung Galaxy S24 Ultra"
                },
                "price": {
                    "description": "Price of the product in decimal format",
                    "type": "number",
                    "example": 1299.99
                },
                "rating": {
                    "description": "Rating of the product (1-5 scale)",
                    "type": "number",
                    "maximum": 5,
                    "minimum": 0,
                    "example": 4.5
                },
                "specifications": {
                    "description": "Technical specifications of the product",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Specification"
                    }
                }
            }
        },
        "domain.Specification": {
            "description": "Technical specification model",
            "type": "object",
            "required": [
                "name",
                "value"
            ],
            "properties": {
                "name": {
                    "description": "Name of the specification",
                    "type": "string",
                    "example": "Display Size"
                },
                "unit": {
                    "description": "Unit of measurement if applicable",
                    "type": "string",
                    "example": "inches"
                },
                "value": {
                    "description": "Value of the specification",
                    "type": "string",
                    "example": "6.8 inches"
                }
            }
        },
        "meli-products-api_pkg_response.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/meli-products-api_pkg_response.ErrorInfo"
                },
                "message": {
                    "type": "string",
                    "example": "Request completed successfully"
                },
                "meta": {
                    "$ref": "#/definitions/meli-products-api_pkg_response.Meta"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "meli-products-api_pkg_response.ErrorInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "PRODUCT_NOT_FOUND"
                },
                "details": {
                    "type": "string",
                    "example": "Please check the product ID and try again"
                },
                "message": {
                    "type": "string",
                    "example": "Product with ID 'INVALID_ID' not found"
                }
            }
        },
        "meli-products-api_pkg_response.Meta": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "page_size": {
                    "type": "integer",
                    "example": 20
                },
                "request_id": {
                    "type": "string",
                    "example": "req-12345-abcde"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "total_count": {
                    "type": "integer",
                    "example": 150
                },
                "total_pages": {
                    "type": "integer",
                    "example": 8
                },
                "version": {
                    "type": "string",
                    "example": "v1"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Products Comparison API",
	Description:      "API for product comparison with detailed product information",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
